services:
  database:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '2773:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kabnet

  kab-connect:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: kab-connect-local
    restart: always
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '8045:8081'
    networks:
      - kabnet

networks:
  kabnet:
    driver: bridge

volumes:
  db_data:
