version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    container_name: telegram-bot
    restart: always
    env_file: .env
    ports:
      - "8082:8081"
    networks:
      - kabnet

networks:
  kabnet:
    driver: bridge
