version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    restart: always
    env_file: .env
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    networks:
      - kabnet

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - kabnet

volumes:
  mongo_data:

networks:
  kabnet:
    driver: bridge
