version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: telegram-bot
    restart: always
    env_file: .env
    ports:
      - '8082:8081'
    networks:
      - kabnet

  database:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  ngrok:
    image: wernight/ngrok
    command: ngrok http bot:3000
    restart: always
    depends_on:
      - bot
    ports:
      - '4040:4040' # NGROK WEB UI.
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}

networks:
  kabnet:
    driver: bridge

volumes:
  db_data:
